// tunk-react/src/pages/Base.jsx
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { connect } from 'tunk-react'
import ReactDOM from 'react-dom';
import 'modules/counter';
import 'modules/counterText';

@connect
class Btn extends Component {

  static propType = {
    count: PropTypes.number.isRequired
  }

  decrement(){
    this.dispatch('counter.decrement');
  }

  render() {
    console.log(this);
    return (
        <button style={{ border:'solid 1px #ccc', 'backgroundColor': '#eee' }} onClick={this.decrement.bind(this)}>-</button>
    )
  }
}


@connect(['counter', 'counterText'],{
  c:'counter'
})
export default class Counter extends Component {

	componentWillReceiveProps(props) {
		const el = ReactDOM.findDOMNode(this.refs.btn1);
		console.log('ReactDOM',{el});
	}

  increment__(){
    this.dispatch('counter.increment');
  }

  render() {

    const { counter:{count}, counterText:{text}} = this.props;

    const { c_increment, c_incrementIfOdd, c_incrementAsync, c_decrement} = this;

    const style = { border:'solid 1px #ccc', 'backgroundColor': '#eee' };

    return (
      <p>
        Clicked: {count}  times
        {' '}
        <button style={style} ref='btn1' onClick={this.increment__.bind(this)}>+</button>
        {' '}
        <Btn/>
        {' '}
        <button style={style} onClick={c_incrementIfOdd}> incrementIfOdd </button>
        {' '}
        <button style={style} onClick={() => c_incrementAsync()}>Increment async</button>
        <br/><br/>
        {text}
      </p>
    )
  }
}

// tunk-vue/src/pages/Base.vue
<template>
  <page>
    Clicked: {{ counter.count }} : times
    <button @click="counter_increment">+</button>
    <button @click="counter_decrement">-</button>
    <button @click="counter_incrementIfOdd">Increment if odd</button>
    <button @click="incrementAsync">Increment async</button>
    <br/> <br/> {{ counterText.text }}
  </page>
</template>
<style>
  button{border:solid 1px #ccc; background-color: #eee;}
</style>
<script>
'use strict';
export default {
  
  state: ['counter', 'counterText'],
  actions: ['counter'],

  components:{
    page: require('./Index.vue')
  },
	created(){

		console.log(this,this.state, this.props);
	},
  methods:{
		incrementAsync(){
      this.counter_incrementAsync();
			//this.dispatch('counter.incrementAsync');
		}
	}
}
</script>
